### ISSUE TITLE
Question: Text Statistics for Other Languages (Korean)

### ISSUE THREAD

**Issue by jeremy-beasley** [cgiffard/TextStatistics.js#3]
Slightly tangential so apologies in advance. 

Do any of you know any text statistics that work with other languages? I'm looking for modifications of these metrics that would work with Korean. 

Thanks for any pointers you could give me.

**Comment by DonaldTsang** [comment]
@jeremybeasley @Amandysha please provide documentation for such test, and ask for a Python implementation in https://github.com/shivam5992/textstat first, that way people can understand such statistics better.
